### ISSUE TITLE
Is there a working example?

### ISSUE THREAD

**Issue by Meusesoft** [EmilAlipiev/SamsungAccessorySDK.Net#2]
Hi, thanks for the work on this. 

I am trying to figure it out how it is supposed to work. Do you have a working example of how to use the SDK package? I looked at the WearCompanion but that works differently.

**Comment by EmilAlipiev** [comment]
Hi, i am planning to write a documentation and even maybe make a video about it later but in mean time. Actually i have some code here https://github.com/EmilAlipiev/SamsungWearCompanion
Maybe this might help you while i try to find a time to complete it with more information. if you need any assist, please dont hesitate to ask me.

**Comment by Meusesoft** [comment]
Thanks. I got a working example now based on SAAgentV2. If have to clean up the code but will share it with you if you are interested.
