### ISSUE TITLE
Simple Working Example

### ISSUE THREAD

**Issue by nikopavl4** [EmilAlipiev/SamsungAccessorySDK.Net#3]
Hello and thank you for the great job,
Is it possible to have a simple working example or a documentation about the package since I am new to Xamarin development?
As I can understand Samsung is not planning to support SAP for Xamarin.Android in the near future, so your package is the only working solution for now.
Thank you in advance.

**Comment by EmilAlipiev** [comment]
Do you need like this one? https://github.com/EmilAlipiev/SamsungWearCompanion
try this maybe first if any question or outdated, i can try to update over the weekend.
